/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ldn.web.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.ldn.service.interfaces.AdsServiceInter;

/**
 * MyEclipse Struts Creation date: 05-12-2015
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag" validate="true"
 */
public class NvchooseAction extends DispatchAction {
	
	@Resource
	private AdsServiceInter adsService;

	public ActionForward staads(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String s_pageNow=request.getParameter("pageNow");
		int pageNow=1;
		if(s_pageNow!=null){
			pageNow=Integer.parseInt(s_pageNow);
		}
		request.setAttribute("currpage", pageNow);
		request.setAttribute("adslist", adsService.showAdsList(10,pageNow));
		int pageCount = adsService.getPageCount(10);
		request.setAttribute("pageCount",pageCount);
		return mapping.findForward("staads");
	}

	public ActionForward staintro(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("staintro");
	}
}