/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ldn.web.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.ldn.domain.Ads;
import com.ldn.domain.Manager;
import com.ldn.domain.Staff;
import com.ldn.service.imp.AdsService;
import com.ldn.service.interfaces.AdsServiceInter;
import com.ldn.web.forms.AdsForm;
import com.ldn.web.forms.StaffForm;


public class PblsadsAction extends DispatchAction {
	
	@Resource
	private AdsServiceInter adsService;

	public AdsServiceInter getAdsService() {
		return adsService;
	}


	public void setAdsService(AdsServiceInter adsService) {
		this.adsService = adsService;
	}


	public ActionForward pblsads(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdsForm adsForm=(AdsForm)form;
		Ads ads= new Ads();
		ads.setAdsname(adsForm.getAdsname());
		ads.setAdscon(adsForm.getAdscon());
		HttpSession session = request.getSession();
		Manager manager = (Manager) session.getAttribute("loginuser");
		ads.setMngid(manager.getMngid());
		adsService.addAds(ads);
		return mapping.findForward("pblsadsok");
	}
}