/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ldn.web.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class StaffForm extends ActionForm {

	private String staid; // 员工编号
	private String staname; // 员工姓名
	private String stadep; // 员工部门
	private String staocp; // 员工职位
	private String stasex; // 员工性别
	private String stapass; // 员工密码
	private String staidt; // 员工身份证号
	private String stabirth; // 员工生日
	private String staphone; // 员工电话号码
	private String staemail; // 员工邮箱
	private String stacrt; // 入职时间
	private String stahon; // 员工荣誉

	public String getStaid() {
		return staid;
	}

	public void setStaid(String staid) {
		this.staid = staid;
	}

	public String getStaname() {
		return staname;
	}

	public void setStaname(String staname) {
		this.staname = staname;
	}

	public String getStaocp() {
		return staocp;
	}

	public void setStaocp(String staocp) {
		this.staocp = staocp;
	}

	public String getStasex() {
		return stasex;
	}

	public void setStasex(String stasex) {
		this.stasex = stasex;
	}

	public String getStapass() {
		return stapass;
	}

	public void setStapass(String stapass) {
		this.stapass = stapass;
	}

	public String getStaidt() {
		return staidt;
	}

	public void setStaidt(String staidt) {
		this.staidt = staidt;
	}

	public String getStabirth() {
		return stabirth;
	}

	public void setStabirth(String stabirth) {
		this.stabirth = stabirth;
	}

	public String getStaphone() {
		return staphone;
	}

	public void setStaphone(String staphone) {
		this.staphone = staphone;
	}

	public String getStaemail() {
		return staemail;
	}

	public void setStaemail(String staemail) {
		this.staemail = staemail;
	}

	public String getStacrt() {
		return stacrt;
	}

	public void setStacrt(String stacrt) {
		this.stacrt = stacrt;
	}

	public String getStahon() {
		return stahon;
	}

	public void setStahon(String stahon) {
		this.stahon = stahon;
	}
	
	public String getStadep() {
		return stadep;
	}

	public void setStadep(String stadep) {
		this.stadep = stadep;
	}



}